-- MySQL Script generated by MySQL Workbench
-- Mon 20 Jun 2016 02:28:41 PM IST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Table `mydb`.`badge_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `badge_types` ;

CREATE TABLE IF NOT EXISTS `badge_types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`badges`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `badges` ;

CREATE TABLE IF NOT EXISTS `badges` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `badge_types_id` INT NOT NULL,
  `category_id` INT(10) UNSIGNED NOT NULL,
  `badge_image` VARCHAR(45) NULL,
  `points` VARCHAR(45) NULL,
  `enable` INT NULL DEFAULT 1,
  `house_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_badges_badge_types1_idx` (`badge_types_id` ASC),
  INDEX `fk_badges_category1_idx` (`category_id` ASC),
  INDEX `fk_badges_house1_idx` (`house_id` ASC),
  CONSTRAINT `fk_badges_badge_types1`
    FOREIGN KEY (`badge_types_id`)
    REFERENCES `badge_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_badges_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_badges_house1`
    FOREIGN KEY (`house_id`)
    REFERENCES `house` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
