-- MySQL Script generated by MySQL Workbench
-- Fri 22 Jul 2016 01:17:41 PM IST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema 
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema

CREATE TABLE IF NOT EXISTS `bundle_assignees` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT(10) UNSIGNED NOT NULL,
  `bundle_id` INT(10) UNSIGNED NOT NULL,
  `updated_at` DATE NULL,
  `created_at` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_buddle_assignee_user1_idx` (`user_id` ASC),
  INDEX `fk_buddle_assignee_buddle1_idx` (`bundle_id` ASC),
  CONSTRAINT `fk_buddle_assignee_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_buddle_assignee_buddle1`
    FOREIGN KEY (`bundle_id`)
    REFERENCES `bundle` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
