-- MySQL Script generated by MySQL Workbench
-- Tue 12 Jul 2016 01:13:29 PM IST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema 
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema 
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table ``.`bundle_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bundle_types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table ``.`bundle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bundle` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `points` INT NULL,
  `avarage_marks` DECIMAL NULL,
  `homegiftcards_id` INT(10) UNSIGNED NOT NULL,
  `dollor_amount` DECIMAL NULL,
  `bundle_types_id` INT NOT NULL,
  `user_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_buddle_homegiftcards1_idx` (`homegiftcards_id` ASC),
  INDEX `fk_buddle_bundle_types1_idx` (`bundle_types_id` ASC),
  INDEX `fk_bundle_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_buddle_homegiftcards1`
    FOREIGN KEY (`homegiftcards_id`)
    REFERENCES `homegiftcards` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_buddle_bundle_types1`
    FOREIGN KEY (`bundle_types_id`)
    REFERENCES `bundle_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bundle_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table ``.`lesson_bundle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lesson_bundle` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `videos_id` INT(10) UNSIGNED NOT NULL,
  `buddle_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table ``.`bundle_assignees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bundle_assignees` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT(10) UNSIGNED NOT NULL,
  `buddle_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_buddle_assignee_user1_idx` (`user_id` ASC),
  INDEX `fk_buddle_assignee_buddle1_idx` (`buddle_id` ASC),
  CONSTRAINT `fk_buddle_assignee_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_buddle_assignee_buddle1`
    FOREIGN KEY (`buddle_id`)
    REFERENCES `bundle` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
